{
 "title": "Quantum Safe Gateway Dashboard",
 "tags": [
  "Main Data Dashboar",
  "Setting"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "content": "![Image](https://media.giphy.com/media/xTiTnxpQ3ghPiB2Hp6/giphy.gif)\t\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 0 },
   "content": "<img src=\"https://assets.rappler.com/612F469A6EA84F6BAE882D2B94A4B421/img/013B46AEB0354E7D9AAD08F2073E2B43/singtel-trustwave-20150408_013B46AEB0354E7D9AAD08F2073E2B43.jpg\" alt=\"Smiley face\" height=\"50\" width=\"120\">"
  },
  {
   "title": "Dashboard Server Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 0 },
   "content": "> IP Address : 192.168.0.100 [] Running Mode: SlaveMode [] UDP Host: ('0.0.0.0', 5005) [] ISP Information: Singtel\n\n"
  },
  {
   "title": "Deployed Gateway Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 2 },
   "targets": [
    {
     "measurement": "gatewaytable",
     "query": "SELECT \"gatewayID\", \"ipAddr\", \"dpdk_c\", \"gwVer\", \"dpdk_v\",  \"dpdk_c\", \"dpdk_e\", \"keyE\" FROM \"gatewaytable\" \n",
     "select": [
      [
       { "params": [ "ipAddr" ], "type": "field" }
      ],
      [
       { "params": [ "dpdk_c" ], "type": "field" }
      ],
      [
       { "params": [ "gwVer" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "content": "\n##### Gateway Throughput Information\n\n---\n\n\n"
  },
  {
   "title": "Gateway Latency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dataVals",
     "select": [
      [
       { "params": [ "latVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fragment",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dataVals",
     "query": "SELECT \"val\" FROM \"latency\" WHERE  $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "frgVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Throughput [Mbps]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "dfsg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dataVals",
     "query": "SELECT \"ival\" FROM \"dataVals\" WHERE (\"Name\" = 'select tag value') AND $timeFilter GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Throughput [Mbps]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "alias": "wqer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dataVals",
     "query": "SELECT \"value\" FROM \"cpu_load_short\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Incoming Throughput:\n- Gate way average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "latency",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "1000",
     "measurement": "dataVals",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "latVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Throughput Speed [Mbps]",
   "type": "graph",
   "description": "Incoming Throughput:\n- Gate way average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "thoughput",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1000",
     "measurement": "dataVals",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "time" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Throughput Speed [Mbps]",
   "type": "graph",
   "description": "Incoming Throughput:\n- Gate way average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "thoughput",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1000",
     "measurement": "dataVals",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TLS Connection Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tlsConn",
     "query": "SELECT \"src\", \"dest\", \"ver\", \"cipher\" FROM \"tlsConn\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}