{
 "title": "Quantum Safe Gateway (Beta v1.1)",
 "description": "Dashboard to show the quantum safe gateway information.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "content": "![Image](https://i.dlpng.com/static/png/405641_preview.png)\t\n"
  },
  {
   "title": "Deployed Gateway Information",
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 0 },
   "content": "<table>\r\n    <caption>Gateway Detail</caption>\r\n    <thead>\r\n        <tr>\r\n            <th colspan=\"2\"><strong>Gateway ID</strong> : Gateway_00 </th>\r\n            <th>IP address: 10.10.10.2 </th>\r\n        </tr>\r\n        <td colspan=\"2\">\r\n        <strong>Quantum Encryption Detail</strong>\r\n        </td>\r\n        <tr>\r\n            <td colspan=\"1\"> <strong>Gateway Version : <br> DPDK Lib Version : <br> Crypt Mode : <br> DPDK Encryption : <br> Key Exchange </strong>\r\n            </td>\r\n            <td colspan=\"3\"> V1.01_beta <br> 19.08 <br> Openssl<br> AES-CBC 256 <br> Customized </td>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n            <th colspan=\"2\"> Deployed Time : 2020-02-07_09:23:12\r\n            <th> GPS Position : [ 1.2988,103.836 ]</th>\r\n        </tr>\r\n        <tr>\r\n            <td colspan=\"1\">Gateway Computer CPU : </td>\r\n            <td colspan=\"3\">Intel(R)i7-8700</td>\r\n        </tr>\r\n        <tr>\r\n            <td colspan=\"1\">Gateway Computer RAM : </td>\r\n            <td colspan=\"3\">8GB-DDR4 1333Hz</td>\r\n        </tr>\r\n    </tbody>\r\n</table>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway Geo-Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "alias": "gateway locaion",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "location",
     "query": "SELECT last(\"latitude\"), last(\"longitude\") FROM \"location\" WHERE (\"Name\" = 'time') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "time" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Latency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dataVals",
     "select": [
      [
       { "params": [ "latVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Incoming Throughput:\n- Gate way average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "latency",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "1000",
     "measurement": "dataVals",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "latVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "content": "![Image](https://www.e92plus.com/img/logos/vendors/trustwave_logo_white.png)\t\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "content": "![Image](https://media.giphy.com/media/xTiTnxpQ3ghPiB2Hp6/giphy.gif)\t\n"
  },
  {
   "title": "Incoming Throughput [Mbps]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "dfsg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dataVals",
     "query": "SELECT \"ival\" FROM \"dataVals\" WHERE (\"Name\" = 'select tag value') AND $timeFilter GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Throughput [Mbps]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "alias": "wqer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dataVals",
     "query": "SELECT \"value\" FROM \"cpu_load_short\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TLS Connection Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tlsConn",
     "query": "SELECT \"src\", \"dest\", \"ver\", \"cipher\" FROM \"tlsConn\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Throughput Speed [Mbps]",
   "type": "graph",
   "description": "Incoming Throughput:\n- Gate way average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "thoughput",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1000",
     "measurement": "dataVals",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "time" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Throughput Speed [Mbps]",
   "type": "graph",
   "description": "Incoming Throughput:\n- Gate way average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "thoughput",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1000",
     "measurement": "dataVals",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentage of Packets Protected by Gateway",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 9, "w": 3, "x": 21, "y": 14 }, "content": "<button> Start </button>\n\n\n" }
 ]
}