{
 "title": "Quantum Safe Gateway (Beta v1.1)",
 "description": "Dashboard to show the quantum safe gateway information.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Control Panel",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway Latency  [ millisecond ]",
   "type": "bargauge",
   "description": "Gateway overhead latency",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Gateway_00",
     "select": [
      [
       { "params": [ "latVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gateway Geo-Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "gateway locaion",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "location",
     "query": "SELECT last(\"latitude\"), last(\"longitude\") FROM \"location\" WHERE (\"Name\" = 'time') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "time" }
     ]
    }
   ]
  },
  {
   "title": "Deployed Gateway Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
   "content": "<table>\r\n    <caption>Gateway Detail</caption>\r\n    <thead>\r\n        <tr>\r\n            <th colspan=\"2\"><strong>Gateway ID</strong> : Gateway_00 </th>\r\n            <th>IP address: 10.10.10.1 </th>\r\n        </tr>\r\n        <td colspan=\"2\">\r\n        <strong>Quantum Encryption Detail</strong>\r\n        </td>\r\n        <tr>\r\n            <td colspan=\"1\"> <strong>Gateway Version  : <!--<br> Crypt Mode : --><br> Encryption : <br> Key Exchange </strong>\r\n            </td>\r\n            <td colspan=\"3\"> V1.01_beta  <br><!-- Openssl<br>--> AES-CBC 256 <br> Customized PQC</td>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n            <th colspan=\"2\"> Deployed Time : 2020-01-30_09:23:12\r\n            <th> GPS Position : [ 1.2988,103.836 ]</th>\r\n        </tr>\r\n        <tr>\r\n            <td colspan=\"1\">Gateway Computer CPU : </td>\r\n            <td colspan=\"3\">Intel(R)i7-8700</td>\r\n        </tr>\r\n        <tr>\r\n            <td colspan=\"1\">Gateway Computer RAM : </td>\r\n            <td colspan=\"3\">8GB-DDR4 1333Hz</td>\r\n        </tr>\r\n    </tbody>\r\n</table>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Gateway average overhead latency.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "latency",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "1000",
     "measurement": "Gateway_00",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "latVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Throughput [Mbps]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "dfsg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Gateway_00",
     "query": "SELECT \"ival\" FROM \"dataVals\" WHERE (\"Name\" = 'select tag value') AND $timeFilter GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Throughput [Mbps]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "alias": "wqer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Gateway_00",
     "query": "SELECT \"value\" FROM \"cpu_load_short\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentage of Packets Protected by Gateway",
   "type": "graph",
   "description": "IP Bypass:\n192.168.0.1",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "1000",
     "measurement": "Gateway_00",
     "query": "SELECT \"encptPct\" FROM \"Gateway_00\" WHERE $timeFilter GROUP BY time($__interval) fill(null) LIMIT 1000",
     "select": [
      [
       { "params": [ "pctVal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quantum-Safe Key Exchange Information",
   "type": "table",
   "description": "Key signature: MD5 value of the encryption key.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "keyEx",
     "query": "SELECT \"val\" FROM \"keyEx\" ",
     "select": [
      [
       { "params": [ "val" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Throughput Speed [Mbps]",
   "type": "graph",
   "description": "Incoming Throughput:\n- Gateway average incoming data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "thoughput",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1000",
     "measurement": "Gateway_00",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "ival" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "time" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Throughput Speed [Mbps]",
   "type": "graph",
   "description": "Outgoing Throughput:\n- Gate way average outgoing data packed speed.\n- unit: Mbps",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "alias": "thoughput",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1000",
     "measurement": "Gateway_00",
     "query": "SELECT last(\"ival\") FROM \"thoughput\" WHERE $timeFilter GROUP BY time($interval) LIMIT 1000",
     "select": [
      [
       { "params": [ "oval" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sniffed TLS Connection Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tlsConn",
     "query": "SELECT \"src\", \"dest\", \"ver\", \"cipher\", \"state\" FROM \"tlsConn\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}